/*
 * This file is generated by jOOQ.
 */
package com.marketplace.eventstore.jdbc.tables;


import com.marketplace.eventstore.jdbc.DefaultSchema;
import com.marketplace.eventstore.jdbc.Keys;
import com.marketplace.eventstore.jdbc.tables.records.ClassifiedAdRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClassifiedAd extends TableImpl<ClassifiedAdRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CLASSIFIED_AD</code>
     */
    public static final ClassifiedAd CLASSIFIED_AD = new ClassifiedAd();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClassifiedAdRecord> getRecordType() {
        return ClassifiedAdRecord.class;
    }

    /**
     * The column <code>CLASSIFIED_AD.ID</code>.
     */
    public final TableField<ClassifiedAdRecord, Integer> ID = createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>CLASSIFIED_AD.CLASSIFIED_AD_ID</code>.
     */
    public final TableField<ClassifiedAdRecord, String> CLASSIFIED_AD_ID = createField(DSL.name("CLASSIFIED_AD_ID"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>CLASSIFIED_AD.APPROVER</code>.
     */
    public final TableField<ClassifiedAdRecord, String> APPROVER = createField(DSL.name("APPROVER"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>CLASSIFIED_AD.OWNER</code>.
     */
    public final TableField<ClassifiedAdRecord, String> OWNER = createField(DSL.name("OWNER"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>CLASSIFIED_AD.TITLE</code>.
     */
    public final TableField<ClassifiedAdRecord, String> TITLE = createField(DSL.name("TITLE"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>CLASSIFIED_AD.TEXT</code>.
     */
    public final TableField<ClassifiedAdRecord, String> TEXT = createField(DSL.name("TEXT"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>CLASSIFIED_AD.PRICE</code>.
     */
    public final TableField<ClassifiedAdRecord, String> PRICE = createField(DSL.name("PRICE"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>CLASSIFIED_AD.PICTURES</code>.
     */
    public final TableField<ClassifiedAdRecord, String> PICTURES = createField(DSL.name("PICTURES"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>CLASSIFIED_AD.CREATED</code>.
     */
    public final TableField<ClassifiedAdRecord, String> CREATED = createField(DSL.name("CREATED"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>CLASSIFIED_AD.UPDATED</code>.
     */
    public final TableField<ClassifiedAdRecord, String> UPDATED = createField(DSL.name("UPDATED"), SQLDataType.CLOB.nullable(false), this, "");

    private ClassifiedAd(Name alias, Table<ClassifiedAdRecord> aliased) {
        this(alias, aliased, null);
    }

    private ClassifiedAd(Name alias, Table<ClassifiedAdRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>CLASSIFIED_AD</code> table reference
     */
    public ClassifiedAd(String alias) {
        this(DSL.name(alias), CLASSIFIED_AD);
    }

    /**
     * Create an aliased <code>CLASSIFIED_AD</code> table reference
     */
    public ClassifiedAd(Name alias) {
        this(alias, CLASSIFIED_AD);
    }

    /**
     * Create a <code>CLASSIFIED_AD</code> table reference
     */
    public ClassifiedAd() {
        this(DSL.name("CLASSIFIED_AD"), null);
    }

    public <O extends Record> ClassifiedAd(Table<O> child, ForeignKey<O, ClassifiedAdRecord> key) {
        super(child, key, CLASSIFIED_AD);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<ClassifiedAdRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_5F;
    }

    @Override
    public List<UniqueKey<ClassifiedAdRecord>> getKeys() {
        return Arrays.<UniqueKey<ClassifiedAdRecord>>asList(Keys.CONSTRAINT_5F);
    }

    @Override
    public ClassifiedAd as(String alias) {
        return new ClassifiedAd(DSL.name(alias), this);
    }

    @Override
    public ClassifiedAd as(Name alias) {
        return new ClassifiedAd(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClassifiedAd rename(String name) {
        return new ClassifiedAd(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClassifiedAd rename(Name name) {
        return new ClassifiedAd(name, null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }
}
