/*
 * This file is generated by jOOQ.
 */
package com.marketplace.eventstore.jdbc.tables.records;


import com.marketplace.eventstore.jdbc.tables.ClassifiedAd;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClassifiedAdRecord extends UpdatableRecordImpl<ClassifiedAdRecord> implements Record10<Integer, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CLASSIFIED_AD.ID</code>.
     */
    public ClassifiedAdRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>CLASSIFIED_AD.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>CLASSIFIED_AD.CLASSIFIED_AD_ID</code>.
     */
    public ClassifiedAdRecord setClassifiedAdId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>CLASSIFIED_AD.CLASSIFIED_AD_ID</code>.
     */
    public String getClassifiedAdId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>CLASSIFIED_AD.APPROVER</code>.
     */
    public ClassifiedAdRecord setApprover(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>CLASSIFIED_AD.APPROVER</code>.
     */
    public String getApprover() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CLASSIFIED_AD.OWNER</code>.
     */
    public ClassifiedAdRecord setOwner(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>CLASSIFIED_AD.OWNER</code>.
     */
    public String getOwner() {
        return (String) get(3);
    }

    /**
     * Setter for <code>CLASSIFIED_AD.TITLE</code>.
     */
    public ClassifiedAdRecord setTitle(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>CLASSIFIED_AD.TITLE</code>.
     */
    public String getTitle() {
        return (String) get(4);
    }

    /**
     * Setter for <code>CLASSIFIED_AD.TEXT</code>.
     */
    public ClassifiedAdRecord setText(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>CLASSIFIED_AD.TEXT</code>.
     */
    public String getText() {
        return (String) get(5);
    }

    /**
     * Setter for <code>CLASSIFIED_AD.PRICE</code>.
     */
    public ClassifiedAdRecord setPrice(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>CLASSIFIED_AD.PRICE</code>.
     */
    public String getPrice() {
        return (String) get(6);
    }

    /**
     * Setter for <code>CLASSIFIED_AD.PICTURES</code>.
     */
    public ClassifiedAdRecord setPictures(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>CLASSIFIED_AD.PICTURES</code>.
     */
    public String getPictures() {
        return (String) get(7);
    }

    /**
     * Setter for <code>CLASSIFIED_AD.CREATED</code>.
     */
    public ClassifiedAdRecord setCreated(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>CLASSIFIED_AD.CREATED</code>.
     */
    public String getCreated() {
        return (String) get(8);
    }

    /**
     * Setter for <code>CLASSIFIED_AD.UPDATED</code>.
     */
    public ClassifiedAdRecord setUpdated(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>CLASSIFIED_AD.UPDATED</code>.
     */
    public String getUpdated() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ClassifiedAd.CLASSIFIED_AD.ID;
    }

    @Override
    public Field<String> field2() {
        return ClassifiedAd.CLASSIFIED_AD.CLASSIFIED_AD_ID;
    }

    @Override
    public Field<String> field3() {
        return ClassifiedAd.CLASSIFIED_AD.APPROVER;
    }

    @Override
    public Field<String> field4() {
        return ClassifiedAd.CLASSIFIED_AD.OWNER;
    }

    @Override
    public Field<String> field5() {
        return ClassifiedAd.CLASSIFIED_AD.TITLE;
    }

    @Override
    public Field<String> field6() {
        return ClassifiedAd.CLASSIFIED_AD.TEXT;
    }

    @Override
    public Field<String> field7() {
        return ClassifiedAd.CLASSIFIED_AD.PRICE;
    }

    @Override
    public Field<String> field8() {
        return ClassifiedAd.CLASSIFIED_AD.PICTURES;
    }

    @Override
    public Field<String> field9() {
        return ClassifiedAd.CLASSIFIED_AD.CREATED;
    }

    @Override
    public Field<String> field10() {
        return ClassifiedAd.CLASSIFIED_AD.UPDATED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getClassifiedAdId();
    }

    @Override
    public String component3() {
        return getApprover();
    }

    @Override
    public String component4() {
        return getOwner();
    }

    @Override
    public String component5() {
        return getTitle();
    }

    @Override
    public String component6() {
        return getText();
    }

    @Override
    public String component7() {
        return getPrice();
    }

    @Override
    public String component8() {
        return getPictures();
    }

    @Override
    public String component9() {
        return getCreated();
    }

    @Override
    public String component10() {
        return getUpdated();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getClassifiedAdId();
    }

    @Override
    public String value3() {
        return getApprover();
    }

    @Override
    public String value4() {
        return getOwner();
    }

    @Override
    public String value5() {
        return getTitle();
    }

    @Override
    public String value6() {
        return getText();
    }

    @Override
    public String value7() {
        return getPrice();
    }

    @Override
    public String value8() {
        return getPictures();
    }

    @Override
    public String value9() {
        return getCreated();
    }

    @Override
    public String value10() {
        return getUpdated();
    }

    @Override
    public ClassifiedAdRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ClassifiedAdRecord value2(String value) {
        setClassifiedAdId(value);
        return this;
    }

    @Override
    public ClassifiedAdRecord value3(String value) {
        setApprover(value);
        return this;
    }

    @Override
    public ClassifiedAdRecord value4(String value) {
        setOwner(value);
        return this;
    }

    @Override
    public ClassifiedAdRecord value5(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public ClassifiedAdRecord value6(String value) {
        setText(value);
        return this;
    }

    @Override
    public ClassifiedAdRecord value7(String value) {
        setPrice(value);
        return this;
    }

    @Override
    public ClassifiedAdRecord value8(String value) {
        setPictures(value);
        return this;
    }

    @Override
    public ClassifiedAdRecord value9(String value) {
        setCreated(value);
        return this;
    }

    @Override
    public ClassifiedAdRecord value10(String value) {
        setUpdated(value);
        return this;
    }

    @Override
    public ClassifiedAdRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClassifiedAdRecord
     */
    public ClassifiedAdRecord() {
        super(ClassifiedAd.CLASSIFIED_AD);
    }

    /**
     * Create a detached, initialised ClassifiedAdRecord
     */
    public ClassifiedAdRecord(Integer id, String classifiedAdId, String approver, String owner, String title, String text, String price, String pictures, String created, String updated) {
        super(ClassifiedAd.CLASSIFIED_AD);

        setId(id);
        setClassifiedAdId(classifiedAdId);
        setApprover(approver);
        setOwner(owner);
        setTitle(title);
        setText(text);
        setPrice(price);
        setPictures(pictures);
        setCreated(created);
        setUpdated(updated);
    }
}
