/*
 * This file is generated by jOOQ.
 */
package com.marketplace.eventstore.jdbc.tables.records;


import com.marketplace.eventstore.jdbc.tables.UserProfile;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserProfileRecord extends UpdatableRecordImpl<UserProfileRecord> implements Record8<String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>user_profile.id</code>.
     */
    public UserProfileRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>user_profile.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>user_profile.firstName</code>.
     */
    public UserProfileRecord setFirstname(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>user_profile.firstName</code>.
     */
    public String getFirstname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>user_profile.lastName</code>.
     */
    public UserProfileRecord setLastname(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>user_profile.lastName</code>.
     */
    public String getLastname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>user_profile.middleName</code>.
     */
    public UserProfileRecord setMiddlename(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>user_profile.middleName</code>.
     */
    public String getMiddlename() {
        return (String) get(3);
    }

    /**
     * Setter for <code>user_profile.displayName</code>.
     */
    public UserProfileRecord setDisplayname(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>user_profile.displayName</code>.
     */
    public String getDisplayname() {
        return (String) get(4);
    }

    /**
     * Setter for <code>user_profile.photos</code>.
     */
    public UserProfileRecord setPhotos(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>user_profile.photos</code>.
     */
    public String getPhotos() {
        return (String) get(5);
    }

    /**
     * Setter for <code>user_profile.created</code>.
     */
    public UserProfileRecord setCreated(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>user_profile.created</code>.
     */
    public String getCreated() {
        return (String) get(6);
    }

    /**
     * Setter for <code>user_profile.updated</code>.
     */
    public UserProfileRecord setUpdated(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>user_profile.updated</code>.
     */
    public String getUpdated() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<String, String, String, String, String, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return UserProfile.USER_PROFILE.ID;
    }

    @Override
    public Field<String> field2() {
        return UserProfile.USER_PROFILE.FIRSTNAME;
    }

    @Override
    public Field<String> field3() {
        return UserProfile.USER_PROFILE.LASTNAME;
    }

    @Override
    public Field<String> field4() {
        return UserProfile.USER_PROFILE.MIDDLENAME;
    }

    @Override
    public Field<String> field5() {
        return UserProfile.USER_PROFILE.DISPLAYNAME;
    }

    @Override
    public Field<String> field6() {
        return UserProfile.USER_PROFILE.PHOTOS;
    }

    @Override
    public Field<String> field7() {
        return UserProfile.USER_PROFILE.CREATED;
    }

    @Override
    public Field<String> field8() {
        return UserProfile.USER_PROFILE.UPDATED;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getFirstname();
    }

    @Override
    public String component3() {
        return getLastname();
    }

    @Override
    public String component4() {
        return getMiddlename();
    }

    @Override
    public String component5() {
        return getDisplayname();
    }

    @Override
    public String component6() {
        return getPhotos();
    }

    @Override
    public String component7() {
        return getCreated();
    }

    @Override
    public String component8() {
        return getUpdated();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getFirstname();
    }

    @Override
    public String value3() {
        return getLastname();
    }

    @Override
    public String value4() {
        return getMiddlename();
    }

    @Override
    public String value5() {
        return getDisplayname();
    }

    @Override
    public String value6() {
        return getPhotos();
    }

    @Override
    public String value7() {
        return getCreated();
    }

    @Override
    public String value8() {
        return getUpdated();
    }

    @Override
    public UserProfileRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public UserProfileRecord value2(String value) {
        setFirstname(value);
        return this;
    }

    @Override
    public UserProfileRecord value3(String value) {
        setLastname(value);
        return this;
    }

    @Override
    public UserProfileRecord value4(String value) {
        setMiddlename(value);
        return this;
    }

    @Override
    public UserProfileRecord value5(String value) {
        setDisplayname(value);
        return this;
    }

    @Override
    public UserProfileRecord value6(String value) {
        setPhotos(value);
        return this;
    }

    @Override
    public UserProfileRecord value7(String value) {
        setCreated(value);
        return this;
    }

    @Override
    public UserProfileRecord value8(String value) {
        setUpdated(value);
        return this;
    }

    @Override
    public UserProfileRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserProfileRecord
     */
    public UserProfileRecord() {
        super(UserProfile.USER_PROFILE);
    }

    /**
     * Create a detached, initialised UserProfileRecord
     */
    public UserProfileRecord(String id, String firstname, String lastname, String middlename, String displayname, String photos, String created, String updated) {
        super(UserProfile.USER_PROFILE);

        setId(id);
        setFirstname(firstname);
        setLastname(lastname);
        setMiddlename(middlename);
        setDisplayname(displayname);
        setPhotos(photos);
        setCreated(created);
        setUpdated(updated);
    }
}
