/*
 * This file is generated by jOOQ.
 */
package com.marketplace.eventstore.jdbc;


import com.marketplace.eventstore.jdbc.tables.EventRecord;
import com.marketplace.eventstore.jdbc.tables.records.EventRecordRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EventRecordRecord> CONSTRAINT_6 = Internal.createUniqueKey(EventRecord.EVENT_RECORD, DSL.name("CONSTRAINT_6"), new TableField[] { EventRecord.EVENT_RECORD.ID }, true);
}
