/*
 * This file is generated by jOOQ.
 */
package com.marketplace.evenstore.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserProfile implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String id;
    private final String firstName;
    private final String lastName;
    private final String middleName;
    private final String displayName;
    private final String photos;
    private final String created;
    private final String updated;

    public UserProfile(UserProfile value) {
        this.id = value.id;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.middleName = value.middleName;
        this.displayName = value.displayName;
        this.photos = value.photos;
        this.created = value.created;
        this.updated = value.updated;
    }

    public UserProfile(
        String id,
        String firstName,
        String lastName,
        String middleName,
        String displayName,
        String photos,
        String created,
        String updated
    ) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.middleName = middleName;
        this.displayName = displayName;
        this.photos = photos;
        this.created = created;
        this.updated = updated;
    }

    /**
     * Getter for <code>user_profile.id</code>.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Getter for <code>user_profile.first_name</code>.
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Getter for <code>user_profile.last_name</code>.
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Getter for <code>user_profile.middle_name</code>.
     */
    public String getMiddleName() {
        return this.middleName;
    }

    /**
     * Getter for <code>user_profile.display_name</code>.
     */
    public String getDisplayName() {
        return this.displayName;
    }

    /**
     * Getter for <code>user_profile.photos</code>.
     */
    public String getPhotos() {
        return this.photos;
    }

    /**
     * Getter for <code>user_profile.created</code>.
     */
    public String getCreated() {
        return this.created;
    }

    /**
     * Getter for <code>user_profile.updated</code>.
     */
    public String getUpdated() {
        return this.updated;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserProfile (");

        sb.append(id);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(middleName);
        sb.append(", ").append(displayName);
        sb.append(", ").append(photos);
        sb.append(", ").append(created);
        sb.append(", ").append(updated);

        sb.append(")");
        return sb.toString();
    }
}
