/*
 * This file is generated by jOOQ.
 */
package com.marketplace.eventstore.jdbc.tables;


import com.marketplace.eventstore.jdbc.DefaultSchema;
import com.marketplace.eventstore.jdbc.Keys;
import com.marketplace.eventstore.jdbc.tables.records.EventDataRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventData extends TableImpl<EventDataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>EVENT_DATA</code>
     */
    public static final EventData EVENT_DATA = new EventData();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EventDataRecord> getRecordType() {
        return EventDataRecord.class;
    }

    /**
     * The column <code>EVENT_DATA.ID</code>.
     */
    public final TableField<EventDataRecord, Integer> ID = createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>EVENT_DATA.EVENT_ID</code>.
     */
    public final TableField<EventDataRecord, String> EVENT_ID = createField(DSL.name("EVENT_ID"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>EVENT_DATA.AGGREGATE_NAME</code>.
     */
    public final TableField<EventDataRecord, String> AGGREGATE_NAME = createField(DSL.name("AGGREGATE_NAME"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>EVENT_DATA.AGGREGATE_ID</code>.
     */
    public final TableField<EventDataRecord, String> AGGREGATE_ID = createField(DSL.name("AGGREGATE_ID"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>EVENT_DATA.EVENT_TYPE</code>.
     */
    public final TableField<EventDataRecord, String> EVENT_TYPE = createField(DSL.name("EVENT_TYPE"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>EVENT_DATA.EVENT_VERSION</code>.
     */
    public final TableField<EventDataRecord, Integer> EVENT_VERSION = createField(DSL.name("EVENT_VERSION"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>EVENT_DATA.DATA</code>.
     */
    public final TableField<EventDataRecord, String> DATA = createField(DSL.name("DATA"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>EVENT_DATA.CREATED</code>.
     */
    public final TableField<EventDataRecord, String> CREATED = createField(DSL.name("CREATED"), SQLDataType.CLOB.nullable(false), this, "");

    private EventData(Name alias, Table<EventDataRecord> aliased) {
        this(alias, aliased, null);
    }

    private EventData(Name alias, Table<EventDataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>EVENT_DATA</code> table reference
     */
    public EventData(String alias) {
        this(DSL.name(alias), EVENT_DATA);
    }

    /**
     * Create an aliased <code>EVENT_DATA</code> table reference
     */
    public EventData(Name alias) {
        this(alias, EVENT_DATA);
    }

    /**
     * Create a <code>EVENT_DATA</code> table reference
     */
    public EventData() {
        this(DSL.name("EVENT_DATA"), null);
    }

    public <O extends Record> EventData(Table<O> child, ForeignKey<O, EventDataRecord> key) {
        super(child, key, EVENT_DATA);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<EventDataRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_5;
    }

    @Override
    public List<UniqueKey<EventDataRecord>> getKeys() {
        return Arrays.<UniqueKey<EventDataRecord>>asList(Keys.CONSTRAINT_5);
    }

    @Override
    public EventData as(String alias) {
        return new EventData(DSL.name(alias), this);
    }

    @Override
    public EventData as(Name alias) {
        return new EventData(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public EventData rename(String name) {
        return new EventData(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EventData rename(Name name) {
        return new EventData(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, String, String, Integer, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
