/*
 * This file is generated by jOOQ.
 */
package com.marketplace.eventstore.jdbc;


import com.marketplace.eventstore.jdbc.tables.ClassifiedAd;
import com.marketplace.eventstore.jdbc.tables.EventData;
import com.marketplace.eventstore.jdbc.tables.FlywaySchemaHistory;
import com.marketplace.eventstore.jdbc.tables.UserProfile;
import com.marketplace.eventstore.jdbc.tables.records.ClassifiedAdRecord;
import com.marketplace.eventstore.jdbc.tables.records.EventDataRecord;
import com.marketplace.eventstore.jdbc.tables.records.FlywaySchemaHistoryRecord;
import com.marketplace.eventstore.jdbc.tables.records.UserProfileRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ClassifiedAdRecord> PK_CLASSIFIED_AD = Internal.createUniqueKey(ClassifiedAd.CLASSIFIED_AD, DSL.name("pk_classified_ad"), new TableField[] { ClassifiedAd.CLASSIFIED_AD.ID }, true);
    public static final UniqueKey<EventDataRecord> PK_EVENT_DATA = Internal.createUniqueKey(EventData.EVENT_DATA, DSL.name("pk_event_data"), new TableField[] { EventData.EVENT_DATA.ID }, true);
    public static final UniqueKey<FlywaySchemaHistoryRecord> PK_FLYWAY_SCHEMA_HISTORY = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("pk_flyway_schema_history"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<UserProfileRecord> PK_USER_PROFILE = Internal.createUniqueKey(UserProfile.USER_PROFILE, DSL.name("pk_user_profile"), new TableField[] { UserProfile.USER_PROFILE.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ClassifiedAdRecord, UserProfileRecord> FK_CLASSIFIED_AD_USER_PROFILE_1 = Internal.createForeignKey(ClassifiedAd.CLASSIFIED_AD, DSL.name("fk_classified_ad_user_profile_1"), new TableField[] { ClassifiedAd.CLASSIFIED_AD.OWNER }, Keys.PK_USER_PROFILE, new TableField[] { UserProfile.USER_PROFILE.ID }, true);
}
