/*
 * This file is generated by jOOQ.
 */
package com.marketplace.eventstore.jdbc;


import com.marketplace.eventstore.jdbc.tables.ClassifiedAd;
import com.marketplace.eventstore.jdbc.tables.EventData;
import com.marketplace.eventstore.jdbc.tables.UserProfile;
import com.marketplace.eventstore.jdbc.tables.records.ClassifiedAdRecord;
import com.marketplace.eventstore.jdbc.tables.records.EventDataRecord;
import com.marketplace.eventstore.jdbc.tables.records.UserProfileRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ClassifiedAdRecord> CONSTRAINT_5F = Internal.createUniqueKey(ClassifiedAd.CLASSIFIED_AD, DSL.name("CONSTRAINT_5F"), new TableField[] { ClassifiedAd.CLASSIFIED_AD.ID }, true);
    public static final UniqueKey<EventDataRecord> CONSTRAINT_5 = Internal.createUniqueKey(EventData.EVENT_DATA, DSL.name("CONSTRAINT_5"), new TableField[] { EventData.EVENT_DATA.ID }, true);
    public static final UniqueKey<UserProfileRecord> CONSTRAINT_C = Internal.createUniqueKey(UserProfile.USER_PROFILE, DSL.name("CONSTRAINT_C"), new TableField[] { UserProfile.USER_PROFILE.ID }, true);
}
