/*
 * This file is generated by jOOQ.
 */
package com.marketplace.eventstore.jdbc;


import com.marketplace.eventstore.jdbc.tables.ClassifiedAd;
import com.marketplace.eventstore.jdbc.tables.EventData;
import com.marketplace.eventstore.jdbc.tables.UserProfile;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>CLASSIFIED_AD</code>.
     */
    public static final ClassifiedAd CLASSIFIED_AD = ClassifiedAd.CLASSIFIED_AD;

    /**
     * The table <code>EVENT_DATA</code>.
     */
    public static final EventData EVENT_DATA = EventData.EVENT_DATA;

    /**
     * The table <code>USER_PROFILE</code>.
     */
    public static final UserProfile USER_PROFILE = UserProfile.USER_PROFILE;
}
