/*
 * This file is generated by jOOQ.
 */
package com.marketplace.evenstore.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClassCache implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String id;
    private final String className;

    public ClassCache(ClassCache value) {
        this.id = value.id;
        this.className = value.className;
    }

    public ClassCache(
        String id,
        String className
    ) {
        this.id = id;
        this.className = className;
    }

    /**
     * Getter for <code>class_cache.id</code>.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Getter for <code>class_cache.class_name</code>.
     */
    public String getClassName() {
        return this.className;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ClassCache (");

        sb.append(id);
        sb.append(", ").append(className);

        sb.append(")");
        return sb.toString();
    }
}
