/*
 * This file is generated by jOOQ.
 */
package com.marketplace.eventstore.jdbc.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserProfile implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String id;
    private final String firstname;
    private final String lastname;
    private final String middlename;
    private final String displayname;
    private final String photos;
    private final String created;
    private final String updated;

    public UserProfile(UserProfile value) {
        this.id = value.id;
        this.firstname = value.firstname;
        this.lastname = value.lastname;
        this.middlename = value.middlename;
        this.displayname = value.displayname;
        this.photos = value.photos;
        this.created = value.created;
        this.updated = value.updated;
    }

    public UserProfile(
        String id,
        String firstname,
        String lastname,
        String middlename,
        String displayname,
        String photos,
        String created,
        String updated
    ) {
        this.id = id;
        this.firstname = firstname;
        this.lastname = lastname;
        this.middlename = middlename;
        this.displayname = displayname;
        this.photos = photos;
        this.created = created;
        this.updated = updated;
    }

    /**
     * Getter for <code>user_profile.id</code>.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Getter for <code>user_profile.firstName</code>.
     */
    public String getFirstname() {
        return this.firstname;
    }

    /**
     * Getter for <code>user_profile.lastName</code>.
     */
    public String getLastname() {
        return this.lastname;
    }

    /**
     * Getter for <code>user_profile.middleName</code>.
     */
    public String getMiddlename() {
        return this.middlename;
    }

    /**
     * Getter for <code>user_profile.displayName</code>.
     */
    public String getDisplayname() {
        return this.displayname;
    }

    /**
     * Getter for <code>user_profile.photos</code>.
     */
    public String getPhotos() {
        return this.photos;
    }

    /**
     * Getter for <code>user_profile.created</code>.
     */
    public String getCreated() {
        return this.created;
    }

    /**
     * Getter for <code>user_profile.updated</code>.
     */
    public String getUpdated() {
        return this.updated;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserProfile (");

        sb.append(id);
        sb.append(", ").append(firstname);
        sb.append(", ").append(lastname);
        sb.append(", ").append(middlename);
        sb.append(", ").append(displayname);
        sb.append(", ").append(photos);
        sb.append(", ").append(created);
        sb.append(", ").append(updated);

        sb.append(")");
        return sb.toString();
    }
}
